name: mm_supermarket
description: Aplikasi Malioboro Mall Supermarket

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  scoped_model: ^1.0.1
  sqflite: ^1.3.1+1
  path_provider: ^1.6.14
  localstorage: ^3.0.2+5
  http: ^0.12.2
  flutter_open_whatsapp: ^0.1.2
  flutter_launcher_icons: ^0.8.0
  search_widget: ^1.0.2
  email_validator: ^1.0.5
  convex_bottom_bar: ^2.4.1
  fluttertoast: ^7.0.4
  firebase_database: ^3.1.1
  firebase_auth: ^0.15.4
  flutter_signin_button: ^1.1.0
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  assets:
    - assets/logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf

  uses-material-design: true
